services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: on-failure
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
